rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
gemfile:
  - gemfiles/Gemfile.rails3
  - gemfiles/Gemfile.rails4
  - gemfiles/Gemfile.rails5
matrix:
  exclude:
    - rvm: 2.2
      gemfile: gemfiles/Gemfile.rails3
    - rvm: 2.3
      gemfile: gemfiles/Gemfile.rails3
    - rvm: 2.4
      gemfile: gemfiles/Gemfile.rails3
    - rvm: 2.0
      gemfile: gemfiles/Gemfile.rails5
    - rvm: 2.1
      gemfile: gemfiles/Gemfile.rails5