require 'active_support/core_ext/array/wrap'
require 'validates_host/shoulda-matchers/domain_name_matcher'
require 'validates_host/shoulda-matchers/host_name_matcher'
require 'validates_host/shoulda-matchers/ip_matcher'
require 'validates_host/shoulda-matchers/subnet_matcher'